"""empty message

Revision ID: 7bf4cc74acec
Revises: 
Create Date: 2021-02-01 21:12:15.727761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf4cc74acec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_motor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=150), nullable=True),
    sa.Column('hora', sa.String(length=150), nullable=True),
    sa.Column('sensor1', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados_motor')
    # ### end Alembic commands ###
